name: circlescreen
description: A simple, modern app for uploading photos to your CircleScreen device.

publish_to: 'none' 
version: 1.0.0+10

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
    

  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  cached_network_image: ^3.3.1
  gal: ^2.2.0
  path_provider: ^2.1.4
  permission_handler: ^12.0.1
  flutter_secure_storage: ^10.0.0
  pin_code_fields: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/toadgurl.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true
